### ISSUE TITLE
`lexxy_render` broken by "undefined method `add_default_name_and_id'" in rails 8.0.3

### ISSUE THREAD

**Issue by kalsan** [basecamp/lexxy#296]
After updating rails to 8.0.3, `lexxy_render` is broken:

`undefined method `add_default_name_and_id' for an instance of ActionView::Helpers::Tags::ActionText`

This happens in the `form.rich_text_area` helper.

**Comment by tomkr4l** [comment]
It's related to https://github.com/rails/rails/issues/55737 and should be fixed with new RoR release.

Workaround for me was to temporarily monkey patch base class.

```ruby
# config/initializers/action_views_tags_base_patch.rb

# remove after upgrade to 8.0.4 and higher
# check https://github.com/rails/rails/issues/55737

module ActionView
  module Helpers
    module Tags
      class Base
        alias_method :add_default_name_and_id_for_value, :add_default_name_and_field_for_value
        alias_method :add_default_name_and_id, :add_default_name_and_field
      end
    end
  end
end
```

**Comment by jorgemanrubia** [comment]
Yes, this was a bug in rails that is already fixed. Thanks
