### ISSUE TITLE
Rails 8.0.3 | add_default_name_and_id error

### ISSUE THREAD

**Issue by thepill** [basecamp/lexxy#234]
Hi there!

lexxy stops working on rails `8.0.3` with the following error message:
```
undefined method 'add_default_name_and_id' for an instance of ActionView::Helpers::Tags::ActionText
```

Thanks and great work 👍

**Comment by cannikin** [comment]
Looks like right here: https://github.com/basecamp/lexxy/blob/main/lib/lexxy/action_text_tag.rb#L12

**Comment by lylo** [comment]
See https://github.com/rails/rails/issues/55737

**Comment by rafaelfranca** [comment]
This is a bug in Rails. We can close this issue. The bug was fixed and will be released in 8.0.4

**Comment by StanBright** [comment]
Thanks @rafaelfranca. It's good to know that it's fixed. I lost 1h+ debugging this yesterday.
